# Generated by Django 5.0 on 2023-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='tech_stack',
            field=models.TextField(),
        ),
    ]
