# Generated by Django 5.0 on 2023-12-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile_github_link_userprofile_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
