# Generated by Django 5.0 on 2023-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
