# Generated by Django 5.0 on 2023-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_project_project_img1_project_project_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img1',
            field=models.ImageField(null=True, upload_to='showcase/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img2',
            field=models.ImageField(null=True, upload_to='showcase/projectimg'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='showcase/profile_pic'),
        ),
    ]
